version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - mysql_db_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: secret
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  server_application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - default
    ports:
    - "9000:9000"
volumes:
  mysql_db_data:
    name: mysql_db_data
  data:
    name: data
  postgres-data:
    name: postgres-data
